name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ESLint
      run: | 
        yarn
        cd frontend
        yarn build
        cd ..
        cd backend
        yarn
        yarn build
        cd ..
    - name: Run tests
      run: |
        cd frontend
        yarn test
        cd ../backend
        yarn test
      # npx eslint . --ext .js,.jsx,.ts,.tsx
