name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd frontend
        yarn
        yarn build
        cd ../backend
        yarn
        yarn build
    - name: Run ESLint
      run: | 
        cd frontend
        yarn add eslint -g 
        yarn add eslint-plugin-react eslint-config-airbnb-typescript  --save-dev
        cd ../backend
        yarn
        yarn add eslint-plugin-react eslint-config-airbnb-typescript  --save-dev
        cd ..
    - name: Run tests
      run: |
        cd frontend
        yarn test
        cd ../backend
        yarn test
